version: '3.8'
services:
  timeless:
    build: .
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/timelessdb
      SPRING_DATASOURCE_USERNAME: timelessuser
      SPRING_DATASOURCE_PASSWORD: timelesspass
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MARIADB_USER: timelessuser
      MARIADB_PASSWORD: timelesspass
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: timelessdb
    ports:
      - "3306:3306"
    volumes:
      - ./volumenes/mariadb_data:/var/lib/mysql
      - /d/volumenes/initDB.sql:/docker-entrypoint-initdb.d/1.sql   # Montar el directorio con los archivos SQL

volumes:
  mariadb_data:
